spring:
  application:
    name: StudentManagement

  datasource:
    url: jdbc:mysql://localhost:3306/studentmanagement?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 1111
